version: 0.2
env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "angular-continuous-deployment-sample"
        BUILD_FOLDER: "dist"
        BUILD_ENV: "prod"
phases:
    install:
        runtime-versions:
            nodejs: 12
        commands:
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - ng build --${BUILD_ENV}
    
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
